### ISSUE TITLE
Compiling dxAutoInstaller from sources requires DevExpress already installed

### ISSUE THREAD

**Issue by alan008** [Delphier/DxAutoInstaller#16]
unit MainFrm in uses clause wants DevExpress modules to be installed (Which version of DexExpress?)

Its a kind of strange when component installer requires THESE components to be already installed.

recompiled installer doesn't work in my case (fails to install my components), I wanted to debug the installert to find the problem, but I can't build installer without DevExpress installed :-(

**Comment by Delphier** [comment]
DxAutoInstaller use TcxTreeList to display component tree, so...

**Comment by kazuser** [comment]
> DxAutoInstaller use TcxTreeList to display component tree, so...

Can't this be replaced with a [standard one](https://blog.marcocantu.com/blog/2021-vcl-features-rad11.html)?

![image](https://github.com/Delphier/DxAutoInstaller/assets/3335273/d75a5d10-a8c8-4322-8721-da3105b7a968)

**Comment by Delphier** [comment]
Standard TreeView does not support multiple columns. If implemented manually, a lot of coding is required, so cxTreeList is used.

**Comment by kazuser** [comment]
👌

**Comment by Delphier** [comment]
At the beginning of the v3 development, I tried to remove the dependency on the DevExpress VCL UI, but I couldn't find a satisfactory alternative. [Virtual TreeView](https://github.com/JAM-Software/Virtual-TreeView) came the closest, but it still falls well short of [TcxTreeList](https://docs.devexpress.com/VCL/170143/ExpressQuantumTreeList/vcl-tree-list), especially when it comes to in-place cell editors and the overall UI experience.

(Once again, I have to admire how powerful and easy to use the DevExpress components are—it's something you truly appreciate only after trying to build a similar application yourself.)

Because of this, the DxAutoInstaller GUI will most likely always depend on the DevExpress VCL components.

That said, the **DxAutoInstaller CLI (`dx.exe`)**, is now available and no longer depends on any DevExpress units.
